apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: reverse-words-build-pipeline
spec:
  workspaces:
  - name: reverse-words-git
  params:
  - name: GIT_SOURCE_URL
    type: string
    default: https://github.com/snehajais22/reverse-words
  - name: imageUrl
    type: string
    default: quay.io/snehajaiswal22/tekton-reversewords
  - name: imageTag
    type: string
    default: latest
    description: Tag for the built image
  tasks:

  - name: fetch-source
    taskRef: 
      name: git-clone
    params:
      - name: url
        value: $(params.GIT_SOURCE_URL)
    workspaces:
      - name: output
        workspace: reverse-words-git

  - name: lint
    taskRef:
      name: golangci-lint
    runAfter:
      - fetch-source
    params:
      - name: package
        value: $(params.GIT_SOURCE_URL)
      - name: flags
        value: --verbose
      - name: GOOS
        value: "linux"
      - name: version
        value: "v1.59.1"
    workspaces:
      - name: source
        workspace: reverse-words-git

  - name: test
    taskRef:
      name: golang-test
    runAfter:
      - lint
    params:
      - name: package
        value: $(params.GIT_SOURCE_URL)
      - name: GOOS
        value: "linux"
    workspaces:
      - name: source
        workspace: reverse-words-git

  - name: build-and-push
    taskRef:
      name: buildah
    runAfter:
      - test
    params:
      - name: DOCKERFILE
        value: ./Dockerfile
      - name: IMAGE
        value: $(params.imageUrl)
      - name: TLSVERIFY
        value: 'false'
      - name: CONTEXT
        value: .
    workspaces:
      - name: source
        workspace: reverse-words-git
