apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-from-dockerfile
spec:
  workspaces:
  - name: source
  params:
  - name: TLSVERIFY
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
    default: "true"
  - name: DOCKERFILE_PATH
    description: Path to the Dockerfile file
    default: ./Dockerfile
  - name: IMAGE_URL
    description: Url for the built image
  - name: IMAGE_TAG
    description: Tag for the built image
    default: latest

  steps:
  - name: build
    image: quay.io/buildah/stable
    workingdir: /workspace/source
    command: ['buildah', 'bud', '--tls-verify=$(params.TLSVERIFY)', '--layers', '-f', '$(params.DOCKERFILE_PATH)', '-t', '$(params.IMAGE_URL):$(params.IMAGE_TAG)', '.']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true

  - name: push
    image: quay.io/buildah/stable
    command: ['buildah', 'push', '--tls-verify=$(params.TLSVERIFY)', '$(params.IMAGE_URL):$(params.IMAGE_TAG)', 'docker://$(params.IMAGE_URL):$(params.IMAGE_TAG)']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true

  volumes:
  - name: varlibcontainers
    emptyDir: {}
