apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: reverseword-build-triggertemplate
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-repo-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: reversewords-build-pipeline-run-
      spec:
        pipelineRef:
          name: reverse-words-build-pipeline
        taskRunSpecs:
          - pipelineTaskName: build-and-push
            taskServiceAccountName: reversewords-pipeline
        params:
          - name: imageTag
            value: $(params.git-revision)
        workspaces:
          - name: reverse-words-git
            persistentVolumeClaim:
                claimName: tekton-workspace

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      name: trigger-1
      template:
        ref: reverseword-build-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
  name: el-webhook
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: el-webhook
    weight: 100
